name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      GIT_USER_EMAIL: "tanyatanya2117@gmail.com"
      GIT_USER_NAME: "Tetiana2117"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Deploy to GitHub Pages
        run: |
          git config user.email "${GIT_USER_EMAIL}"
          git config user.name "${GIT_USER_NAME}"
          npm run deploy
        env:
          CI: true
